"""Pydantic request/response models for navigation and translation endpoints."""
from __future__ import annotations

from pydantic import BaseModel, Field, field_validator


class NavigationRequest(BaseModel):
    """Request payload for the /api/navigate endpoint."""

    from_location: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="Starting location (gate, section, facility, or parking area)",
    )
    to_location: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="Destination location",
    )
    accessibility: bool = Field(
        default=False,
        description="When True, only wheelchair-accessible routes are returned",
    )
    language: str = Field(
        default="en",
        description="ISO 639-1 language code for the directions",
    )


class NavigationResponse(BaseModel):
    """Step-by-step walking directions between two stadium locations."""

    from_location: str = Field(..., description="Validated start location")
    to_location: str = Field(..., description="Validated destination")
    directions: str = Field(..., description="Numbered walking directions generated by Gemini")
    accessibility: bool = Field(..., description="Whether the accessibility routing constraint was applied")
    mock: bool = Field(default=False, description="True when directions came from the mock engine")


class TranslationRequest(BaseModel):
    """Request payload for the /api/translate endpoint."""

    text: str = Field(
        ...,
        min_length=1,
        max_length=2_000,
        description="Text to translate (max 2 000 characters)",
    )
    target_language: str = Field(
        ...,
        description="ISO 639-1 target language code",
    )

    @field_validator("text")
    @classmethod
    def text_not_blank(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Text must not be blank or whitespace only.")
        return v


class TranslationResponse(BaseModel):
    """Translation result from the /api/translate endpoint."""

    original_text: str = Field(..., description="The source text that was translated")
    translated_text: str = Field(..., description="The translated text")
    target_language: str = Field(..., description="The ISO 639-1 code of the target language")
    mock: bool = Field(default=False, description="True when the translation came from the mock engine")


class StadiumInfo(BaseModel):
    """Static stadium configuration returned by /api/info."""

    name: str = Field(..., description="Stadium display name")
    total_capacity: int = Field(..., gt=0, description="Maximum fan capacity")
    zones: list[str] = Field(..., description="List of monitored crowd zones")
    facilities: list[str] = Field(..., description="All named facilities in the stadium")
    gates: list[str] = Field(..., description="Public entry gates")
