/**
 * SIGNAL — Crowd Monitor Tab Module
 * Fetches live zone data, renders density cards and heatmap bars,
 * and generates Gemini-powered AI advisories.
 */

const CrowdTab = (() => {
  let autoRefreshTimer = null;
  let lastUpdated = null;

  // ── Colour ramp for density bars ──────────────────────────
  function densityColor(density) {
    if (density >= 90) return '#e74c3c';
    if (density >= 80) return '#e67e22';
    if (density >= 60) return '#f1c40f';
    return '#1a8a4a';
  }

  // ── Render a single zone card ─────────────────────────────
  function renderZoneCard(zoneKey, data) {
    const color = densityColor(data.density);
    const alertClass = data.alert ? 'alert' : '';
    const fans = data.fan_count.toLocaleString();

    return `
      <article class="zone-card ${alertClass}" 
               aria-label="${data.zone}: ${data.density}% capacity, ${data.status}">
        <div class="zone-header">
          <div>
            <div class="zone-name">${data.zone}</div>
            <div class="zone-count">~${fans} fans</div>
          </div>
          <span class="status-badge ${data.status}" role="status">
            ${data.status}
          </span>
        </div>
        <div class="density-bar-track" 
             role="progressbar" 
             aria-valuenow="${data.density}" 
             aria-valuemin="0" 
             aria-valuemax="100"
             aria-label="${data.zone} capacity">
          <div class="density-bar-fill" 
               style="width: ${data.density}%; background: ${color};"></div>
        </div>
        <div class="zone-density-label">
          <span>Capacity</span>
          <span class="density-number" style="color:${color};">${data.density}%</span>
        </div>
      </article>`;
  }

  // ── Fetch and render crowd status ─────────────────────────
  async function loadCrowdStatus() {
    const grid   = document.getElementById('crowd-zone-grid');
    const statsEl = document.getElementById('crowd-stats');
    const lastEl  = document.getElementById('crowd-last-updated');

    if (!grid) return;

    try {
      const data = await window.API.get('/crowd/status');

      // Render zone cards
      grid.innerHTML = Object.entries(data.zones)
        .map(([key, zone]) => renderZoneCard(key, zone))
        .join('');

      // Update summary stats
      if (statsEl) {
        statsEl.innerHTML = `
          <div class="summary-stat">
            <div class="stat-number">${data.overall_density}%</div>
            <div class="stat-label">Overall Capacity</div>
          </div>
          <div class="summary-stat">
            <div class="stat-number">${data.total_fans.toLocaleString()}</div>
            <div class="stat-label">Total Fans</div>
          </div>
          <div class="summary-stat">
            <div class="stat-number">${data.alert_zones}</div>
            <div class="stat-label">Alert Zones</div>
          </div>
        `;
      }

      lastUpdated = new Date();
      if (lastEl) lastEl.textContent = `Updated ${lastUpdated.toLocaleTimeString()}`;

    } catch (err) {
      if (grid) grid.innerHTML = `<p class="advisory-text" style="color:var(--text-muted)">⚠️ Could not load crowd data. Is the server running?</p>`;
    }
  }

  // ── Fetch and display AI advisory ─────────────────────────
  async function loadAdvisory() {
    const advisoryEl  = document.getElementById('advisory-text');
    const advisoryBtn = document.getElementById('advisory-btn');

    if (!advisoryEl) return;

    advisoryEl.textContent = '⏳ Generating AI advisory…';
    if (advisoryBtn) { advisoryBtn.disabled = true; }

    try {
      const data = await window.API.get('/crowd/advisory');
      advisoryEl.textContent = data.advisory;

      const metaEl = document.getElementById('advisory-meta');
      if (metaEl) {
        metaEl.textContent = data.mock
          ? 'Generated by SIGNAL mock engine'
          : `Generated by Gemini AI · ${new Date().toLocaleTimeString()}`;
      }
    } catch (err) {
      advisoryEl.textContent = `⚠️ Advisory unavailable: ${err.message}`;
    } finally {
      if (advisoryBtn) { advisoryBtn.disabled = false; }
    }
  }

  // ── Toggle auto-refresh ───────────────────────────────────
  function toggleAutoRefresh(enabled) {
    if (enabled) {
      autoRefreshTimer = setInterval(loadCrowdStatus, 15_000);
      window.showToast('Auto-refresh enabled (every 15s)', 'success');
    } else {
      clearInterval(autoRefreshTimer);
      window.showToast('Auto-refresh disabled', 'info');
    }
  }

  // ── Called when the Crowd tab becomes active ──────────────
  function onActivate() {
    loadCrowdStatus();
    loadAdvisory();
  }

  // ── Initialise ────────────────────────────────────────────
  function init() {
    const refreshBtn  = document.getElementById('crowd-refresh-btn');
    const advisoryBtn = document.getElementById('advisory-btn');
    const autoToggle  = document.getElementById('auto-refresh-toggle');

    if (refreshBtn)  refreshBtn.addEventListener('click', loadCrowdStatus);
    if (advisoryBtn) advisoryBtn.addEventListener('click', loadAdvisory);
    if (autoToggle) {
      autoToggle.addEventListener('change', e => toggleAutoRefresh(e.target.checked));
    }
  }

  return { init, onActivate, loadCrowdStatus, loadAdvisory };
})();

document.addEventListener('DOMContentLoaded', CrowdTab.init);
window.CrowdTab = CrowdTab;
